-- Frontier Education Project / EdTech Map
-- Run first in Supabase SQL Editor.

create table if not exists public.policies (
  id bigint generated by default as identity primary key,
  state_code varchar(2) not null,
  state_name text not null,
  title text not null,
  summary text not null,
  category text not null,
  status text not null,
  effective_date date null,
  source_url text not null,
  last_updated date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint policies_state_code_format check (state_code ~ '^[A-Z]{2}$'),
  constraint policies_category_check check (category in ('AI Use','Student Privacy','Parental Consent','AI Literacy','School Procurement')),
  constraint policies_status_check check (status in ('Enacted','Pending','Guidance','Regulation')),
  constraint policies_unique_source unique (state_code, title, source_url)
);

create index if not exists idx_policies_state_code on public.policies (state_code);
create index if not exists idx_policies_category on public.policies (category);
create index if not exists idx_policies_status on public.policies (status);
create index if not exists idx_policies_state_category_status on public.policies (state_code, category, status);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_policies_set_updated_at on public.policies;
create trigger trg_policies_set_updated_at
before update on public.policies
for each row execute function public.set_updated_at();

-- Browser access stays closed; Express uses the Supabase service-role key.
alter table public.policies enable row level security;
