create table if not exists public.site_submissions (
  id bigint generated by default as identity primary key,
  submission_type text not null check (submission_type in ('newsletter', 'contact')),
  name text,
  email text not null,
  inquiry_type text,
  message text,
  notification_status text not null default 'pending'
    check (notification_status in ('pending', 'sent', 'failed', 'disabled')),
  notified_at timestamptz,
  notification_error text,
  created_at timestamptz not null default now()
);

create index if not exists site_submissions_type_created_idx
  on public.site_submissions (submission_type, created_at desc);

create index if not exists site_submissions_notification_status_idx
  on public.site_submissions (notification_status, created_at desc);

alter table public.site_submissions enable row level security;

-- No anon/authenticated policies are created intentionally.
-- The Node backend writes using the server-side Supabase secret/service-role key.
